name: flame_game
description: FlameGame Flame game
version: 0.0.0
publish_to: none

environment:
  sdk: ^2.17.0
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.8.1

flutter:
  assets:
    - assets/images/